### ISSUE TITLE
相册授权 选择部分图片给授权弹框 出现不可点击

### ISSUE THREAD

**Issue by qwerOC** [li6185377/IMYAppGrayStyle#3]

**Comment by wscqs** [comment]
确实有这问题，我集成也遇到

**Comment by ioscell** [comment]
我这也是，H5拉起相册，导致相册不可点击
![SCR-20230217-nm7](https://user-images.githubusercontent.com/10095472/219599951-c9516a8e-d7ff-4975-8193-ec4f45b49e88.png)

**Comment by wscqs** [comment]
来信已经收到。

**Comment by li6185377** [comment]
目前网安那边一般只要求 首页置灰就行了， 所以小伙伴们可以不用加 window 上，加载 ViewController.view 上即可。 全局window确实有坑
